### ISSUE TITLE
Some list suggestions. 

### ISSUE THREAD

**Issue by prabhath6** [smoqadam/python-tips#3]
These are some the ways how i work with lists, which help me save time.
### 1. Copy a List.

``` python
a = [1, 2, 3, 4]
''' Considered as one of the weirdest syntax to copy elements.'''
a_copy = a[:]
```
### 2. Create a list out of string.

``` python
data = "abcd"
data_list = []

for i in data:
    data_list.append(i)

# OutPut: data_list = ['a', 'b', 'c', 'd'] 

''' The above process can be simplified as below. '''
data_list2 = list(data)  # OutPut: data_list = ['a', 'b', 'c', 'd'] 
```

There are many other but these are what i use on a regular basis.

I would like to make one suggestion regarding the readme file. I saw that you were having all the topics clubbed in to one, instead of that make a separate section for each of it, like let Lists be the main section and you have subsections under lists. This would help if anyone is looking for a particular section.

**Comment by smoqadam** [comment]
Hi
thanks for your tips. I added to the list.
I'll separate as soon as possible. Thanks for your suggestions.
